### ISSUE TITLE
Text stays on black background when switching to whiteboard

### ISSUE THREAD

**Issue by Naereen** [tableaunoir/tableaunoir.github.io#20]
See this small gif:
![Peek 05-11-2020 09-28](https://user-images.githubusercontent.com/11994719/98221521-06fcaf00-1f50-11eb-96dd-54a54d164972.gif)
Maybe the text magnets could be "inverted" to white-on-black instead of staying "black-on-white", when switching from blackboard to whiteboard ?

Note: this feature is really not so urgent or important.

**Comment by francoisschwarzentruber** [comment]
Thank you! Solved by using the library https://github.com/Viglino/jCSSRule

**Comment by Naereen** [comment]
The fix is perfect!
