### ISSUE TITLE
Weird bug when using text input/magnets: if text is too long (to the right), view is moved and menu is lost

### ISSUE THREAD

**Issue by Naereen** [tableaunoir/tableaunoir.github.io#22]
I encountered a weird bug when using text input/magnets: if text is too long (to the right), view is moved and menu is lost.
See this big:
![Peek 05-11-2020 14-39](https://user-images.githubusercontent.com/11994719/98248223-f0b51a00-1f74-11eb-8807-9739255739aa.gif)
I cannot think of a solution...

One solution to never loose the menu would be to use absolute coordinate to display the menu, no matter the state and position of the drawing canvas below it.

**Comment by francoisschwarzentruber** [comment]
Well done! I love your video. The last commit "solves" your issue. I do not like the way I solved it but that is a hack, but it does the job.

**Comment by Naereen** [comment]
I haven't seen this fix, thanks and good job!
If you don't mind, I will keep testing the tools very regularly, and trying to find small bugs like this.
