### ISSUE TITLE
Magnet creation

### ISSUE THREAD

**Issue by guywiz** [tableaunoir/tableaunoir.github.io#6]
Not clear -- from the app documentation available online -- how one must proceed to create a magnet from a drawing. I only saw how to import pre-existing magnets on my board. Not clear either from the youtube tutorial.

**Comment by francoisschwarzentruber** [comment]
Dear guywiz,
thank you for your message. To create a magnet, draw a contour and then press Ctrl+X.
Because of your message, I added a tab "Help" in the menu, that answers your question.

**Comment by guywiz** [comment]
Thanks for being so quick! Works fine.

**Comment by pchampin** [comment]
Just to say that I simply LOVE this feature :-)
