### ISSUE TITLE
Backgrounds! (for instance for teaching music)

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir.github.io#9]
Tableaunoir can be helpful for teaching music notation. There is a background with two staffs. If you have ideas for adding other backgrounds, or want to contribute on that issue, do not hesitate!

**Comment by Naereen** [comment]
I don't understand if this is a feature request, or an announce for a new feature.

**Comment by francoisschwarzentruber** [comment]
This feature request may consist in adding other types of backgrounds.
